[theme]

# Primary accent for interactive elements
primaryColor = '#6eb52f'

# Background color for the main content area
backgroundColor = '#f0f0f5'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#e0e0ef'

# Color used for almost all text
textColor = '#262730'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
